// src/components/ColorPreview.tsx
import { type Component, createMemo } from "solid-js";
import { useClipboard, whenever } from "solidjs-use";
import Toast from "bootstrap/js/dist/toast";

interface ColorPreviewProps {
  color: string;
  textColor: string;
  class?: string;
}

export const ColorPreview: Component<ColorPreviewProps> = (props) => {
  const { copied, copy } = useClipboard({
    source: () => props.color,
  });

  whenever(copied, () => {
    const toastBootstrap = Toast.getOrCreateInstance("#clipToast");

    toastBootstrap.show();
  });

  const classList = createMemo(() => {
    return `btn bg-color font-monospace opacify ${props.class}`;
  });

  return (
    <button
      class={classList()}
      style={{
        "background-color": props.color,
        "border-color": props.textColor,
        color: props.textColor,
      }}
      onClick={() => copy()}
      title="Copiar color al portapapeles"
    >
      {props.color}
    </button>
  );
};

// components/ColorPreview.vue
<template lang="pug">
tippy(content="Copiar color", arrow)
  button.bg-color.p-2.border.border-solid.rounded-md.text-sm.font-mono.opacify(
    @click.stop="() => copy()"
  ) {{ color }}
</template>

<script setup lang="ts">
import { Tippy } from "vue-tippy";
const props = defineProps<{
  color: string;
  textColor: string;
}>();

const { copy, copied } = useClipboard({
  source: () => props.color,
});

const { $toast } = useNuxtApp();

whenever(copied, () => {
  $toast.success("Color copiado al portapapeles");
});
</script>

<style lang="scss" scoped>
.bg-color {
  background-color: v-bind("color");
  border-color: v-bind("textColor") !important;
  color: v-bind("textColor");
}
</style>
